'use strict';

const ARGUMENTS = {
  VERSION: `version`,
  HELP: `help`,
  GENERATE: `generate`,
};
const DEFAULT_COUNT = 1;
const MAX_COUNT = 1000;
const MIN_SENTENCES_IN_ANNOUNCE = 1;
const MAX_SENTENCES_IN_ANNOUNCE = 5;
const MIN_SENTENCES_IN_FULL_TEXT = 1;
const MIN_CATEGORIES_NUMBER = 1;
const EXIT_CODES = {
  SUCCESS: 0,
};
const MOCK_FILE_NAME = `mock.json`;
const DATE_FORMAT = `yyyy-mm-dd hh:MM:ss`;
const MONTH_MOCK_COUNTER = 3;

module.exports = {
  ARGUMENTS,
  DEFAULT_COUNT,
  MAX_COUNT,
  MIN_SENTENCES_IN_ANNOUNCE,
  MAX_SENTENCES_IN_ANNOUNCE,
  MIN_SENTENCES_IN_FULL_TEXT,
  MIN_CATEGORIES_NUMBER,
  EXIT_CODES,
  MOCK_FILE_NAME,
  DATE_FORMAT,
  MONTH_MOCK_COUNTER,
};
